set shell := ["fish", "-c"]

DATE_TAG := `date +"%Y-%m-%d"`

[arg("nojj", long="nojj", value="true")]
@release nojj="false": check-dirty
    # cross compile the host binary for aarch64
    cross build --release 

    # by default (unless --nojj is passed):
    # move main tag to the the last commit (this one is clean)
    if [ {{nojj}} = "false" ]; \
        jj b m main -t @-; \
        jj git push; \
    end

    # requires glab cli to be installed and authenticated
    glab release create v{{DATE_TAG}} 'target/aarch64-unknown-linux-gnu/release/host#cryostorage_aarch64' \
        --name "Cryostorage Host v{{DATE_TAG}}" \
        --notes "Release of the aarch64 host binary for the cryostorage chamber."

@check-dirty:
    if jj status | rg -q "Working copy changes:"; \
        echo "⚠️  The jj repository is dirty – uncommitted changes detected."; \
        exit 1; \
    end

