export global Const {
    out property <length> big_switch_height: 160px;
    out property <length> border_radius_large: 20px;
    out property <length> border_radius_small: 10px;
    out property <length> border_spacing: 20px;
    out property <length> button_pictogram: 160px;
    out property <length> button_height: 80px;
    out property <length> button_width_regular: 160px;
    out property <length> button_height_regular: 50px;
    out property <length> edge_spacing: 50px;
    out property <length> element_width_short: 300px;
    out property <length> element_width_wide: 400px;
    out property <length> info_height: 120px;
    out property <length> light_dia: 160px;
    out property <length> padding_large: 20px;
    out property <length> padding_small: 10px;
    out property <length> small_switch_height: 90px;
    out property <length> screen_width: 1280px;
    out property <length> screen_height: 800px;
    out property <length> tab_button_width: 150px;
    // Properties for vacuum drawing
    out property <length> vacuum_image_status_circle_size: 20.256px;
    // calculated properties
    out property <length> useable_width: screen_width - tab_button_width;
}

