import { Const } from "consts.slint";
import { Palette } from "palette.slint";
import { LineEdit } from "std-widgets.slint";
import { Logic, ValveOrPumpState } from "logic.slint";

export component NormalText inherits Text {
    font-size: 20px;
    color: Palette.text;
}

export component H1Text inherits NormalText {
    font-size: 40px;
    font-weight: 800;
}

export component H2Text inherits NormalText {
    font-size: 30px;
    font-weight: 600;
}

export component H3Text inherits NormalText {
    font-size: 25px;
    font-weight: 400;
}

export component MyWindow inherits Rectangle {
    in-out property <int> index;
    in property <int> current_index;

    visible: self.index == self.current_index ? true : false;

    x: Const.tab_button_width;
    y: 0px;
    width: Const.screen_width - Const.tab_button_width;
    height: Const.screen_height;
}

export component MyHorizontalLayout inherits HorizontalLayout {
    alignment: space-between;
    padding-left: Const.border_spacing;
    padding-right: Const.border_spacing;
    spacing: Const.border_spacing;
}

export component MyVerticalLayout inherits VerticalLayout {
    alignment: space-between;
    padding-top: Const.border_spacing;
    padding-bottom: Const.border_spacing;
    spacing: Const.border_spacing;
}

// Default tab button component that should be standing on the right side of the screen
export component TabButton inherits Rectangle {
    in-out property <int> index;
    in property <int> current_index;
    in property <image> icon;

    x: 0px;
    y: self.height * index;
    width: Const.tab_button_width;
    height: Const.screen_height / 4;

    background: (root.current_index) == index ? Palette.bg_overlay : Palette.bg_inact;

    border-top-right-radius: 30px;
    border-bottom-right-radius: 30px;

    Image {
        width: 50%;
        source: icon;
        colorize: Palette.flamingo;
    }
}

export component LightSwitch inherits Rectangle {
    in-out property <bool> activated: false;
    callback clicked(bool);

    width: Const.light_dia;
    height: Const.light_dia;

    border-radius: Const.light_dia / 2;

    background: activated ? Palette.button_on : Palette.button_off;

    Image {
        source: activated ? @image-url("imgs/light_on.svg") : @image-url("imgs/light_off.svg");
        colorize: activated ? Palette.yellow : Palette.subtext1;
        width: 75%;
    }

    TouchArea {
        clicked => {
            activated = !activated;
            root.clicked(activated);
        }
    }
}

export component InfoArea inherits Rectangle {
    in-out property <string> title: "Info area";
    in-out property <string> text: " 150 K";
    in-out property <color> text_color: Palette.text;

    width: Const.element_width_wide;
    height: Const.info_height;

    background: Palette.bg_area;

    border-radius: Const.border_radius_large;

    VerticalLayout {
        padding: Const.padding_large;

        H3Text {
            text: root.title;
            horizontal-alignment: center;
        }

        H2Text {
            text: root.text;
            horizontal-alignment: center;
            vertical-alignment: center;
            color: root.text_color;
        }
    }
}

export component InfoAreaSmall inherits InfoArea {
    width: Const.element_width_short;
}

export component TemperatureArea inherits InfoAreaSmall {
    in property <int> temperature: 0;

    text_color: (Logic.sample_temp > 0 && Logic.sample_temp < 120) ? Palette.blue : Palette.red;
    text: (temperature == 0) ? "Error" : temperature + " K";
}

export component StatusOkErr inherits Rectangle {
    in property <string> title: "StatusOkErr Field";
    in-out property <bool> ok: true;

    width: Const.element_width_wide;
    height: Const.button_height;

    border-radius: Const.border_radius_large;

    background: Palette.bg_area;

    HorizontalLayout {
        padding: Const.padding_large;
        H3Text {
            text: root.title;
            horizontal-alignment: center;
            vertical-alignment: center;
            color: Palette.text;
        }

        Image {
            source: root.ok ? @image-url("imgs/check.svg") : @image-url("imgs/cross.svg");
            colorize: root.ok ? Palette.green : Palette.red;
        }
    }
}

export component LongButton inherits Rectangle {
    in property <string> text: "Long Button";
    in property <bool> enabled: Logic.admin_mode;
    callback clicked();

    width: Const.element_width_wide;
    height: Const.button_height_regular;

    border-radius: Const.border_radius_small;

    ta := TouchArea {
        clicked => {
            if (root.enabled) {
                root.clicked();
            }
        }
    }

    background: enabled ? (!ta.pressed ? Palette.button_off : Palette.button_on) : Palette.button_off;

    NormalText {
        text: root.text;
        horizontal-alignment: center;
        vertical-alignment: center;
        color: enabled ? Palette.text : Palette.button_inactive_text;
    }
}

export component ShortButton inherits LongButton {
    width: Const.element_width_short;
}

export component RegularButton inherits Rectangle {
    in property <string> text: "Regular Button";
    in property <bool> enabled: Logic.admin_mode;
    callback clicked();

    width: Const.button_width_regular;
    height: Const.button_height_regular;

    border-radius: Const.border_radius_large;

    ta := TouchArea {
        clicked => {
            if (root.enabled) {
                root.clicked();
            }
        }
    }

    background: enabled ? (!ta.pressed ? Palette.button_off : Palette.button_on) : Palette.button_off;

    NormalText {
        text: root.text;
        horizontal-alignment: center;
        vertical-alignment: center;
        color: enabled ? Palette.text : Palette.button_inactive_text;
    }
}

export component BigSwitch inherits Rectangle {
    in-out property <bool> right_side: false;
    in-out property <string> title: "Big Switch";
    in-out property <string> left_text: "Left";
    in-out property <string> right_text: "Right";
    in property <bool> enabled: Logic.admin_mode;
    callback switched(bool);

    width: Const.element_width_wide;
    height: Const.big_switch_height;

    background: Palette.bg_area;
    border_radius: Const.border_radius_large;

    VerticalLayout {
        padding: Const.padding_large;
        H2Text {
            text: root.title;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            Rectangle {
                width: 45%;
                height: 30%;
                background: root.right_side ? Palette.button_off : Palette.button_on;

                border-top-left-radius: Const.border_radius_small;
                border-bottom-left-radius: Const.border_radius_small;

                TouchArea {
                    clicked => {
                        if (root.enabled) {
                            root.switched(false);
                        }
                    }
                }

                H3Text {
                    text: root.left_text;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: root.enabled ? Palette.text : Palette.button_inactive_text;
                }
            }

            Rectangle {
                width: 45%;
                height: 30%;
                background: !root.right_side ? Palette.button_off : Palette.button_on;

                border-top-right-radius: Const.border_radius_small;
                border-bottom-right-radius: Const.border_radius_small;

                TouchArea {
                    clicked => {
                        if (root.enabled) {
                            root.switched(true);
                        }
                    }
                }

                H3Text {
                    text: root.right_text;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: root.enabled ? Palette.text : Palette.button_inactive_text;
                }
            }
        }
    }
}

export component SmallSwitch inherits Rectangle {
    in-out property <bool> right_side: false;
    in property <string> title: "Small Switch";
    in property <string> left_text: "Left";
    in property <string> right_text: "Right";
    in property <bool> enabled: Logic.admin_mode;
    callback switched(bool);

    width: Const.element_width_short;
    height: Const.small_switch_height;

    background: Palette.bg_area;
    border_radius: Const.border_radius_large;

    VerticalLayout {
        padding: Const.padding_small;
        H3Text {
            text: root.title;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            Rectangle {
                width: 45%;
                height: 30px;
                background: root.right_side ? Palette.button_off : Palette.button_on;

                border-top-left-radius: Const.border_radius_small;
                border-bottom-left-radius: Const.border_radius_small;

                TouchArea {
                    clicked => {
                        if (root.enabled) {
                            root.switched(false);
                        }
                    }
                }

                NormalText {
                    text: root.left_text;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: root.enabled ? Palette.text : Palette.button_inactive_text;
                }
            }

            Rectangle {
                width: 45%;
                height: 30px;
                background: !root.right_side ? Palette.button_off : Palette.button_on;

                border-top-right-radius: Const.border_radius_small;
                border-bottom-right-radius: Const.border_radius_small;

                TouchArea {
                    clicked => {
                        if (root.enabled) {
                            root.switched(true);
                        }
                    }
                }

                NormalText {
                    text: root.right_text;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: root.enabled ? Palette.text : Palette.button_inactive_text;
                }
            }
        }
    }
}

export component PictogramButton inherits Rectangle {
    in property <image> icon: @image-url("imgs/door.svg");
    in property <bool> enabled: Logic.admin_mode;
    callback clicked();

    width: Const.button_pictogram;
    height: Const.button_pictogram;

    border-radius: Const.border_radius_large;

    ta := TouchArea {
        clicked => {
            if (root.enabled) {
                root.clicked();
            }
        }
    }

    background: root.enabled && ta.pressed ? Palette.button_on : Palette.button_off;

    Image {
        source: root.icon;
        colorize: root.enabled ? Palette.text : Palette.button_inactive_text;
        width: 50%;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}

export component MyLineEdit inherits LineEdit {
    font-size: 20px;
}

export component VacuumStateCircle inherits Rectangle {
    in property <ValveOrPumpState> state: ValveOrPumpState.UndefinedOrError;

    width: Const.vacuum_image_status_circle_size;
    height: Const.vacuum_image_status_circle_size;
    border-radius: self.width / 2;
    border-width: 0px;

    background: state == ValveOrPumpState.OpenOrOn ? Palette.green : (state == ValveOrPumpState.ClosedOrOff ? Palette.blue : (state == ValveOrPumpState.SetDifferentFromCalled ? Palette.peach : Palette.red));
}
