import { Const } from "consts.slint";
import { Palette } from "palette.slint";


// Structs
export struct BakingTime {
    hours: int,
    minutes: int,
    seconds: int,
}

// Valve and pump states
export enum ValveOrPumpState {
    OpenOrOn,
    ClosedOrOff,
    UndefinedOrError,
    SetDifferentFromCalled
}

// Logic
export global Logic {
    // Baking
    in-out property <bool> baking_is_enabled;
    in-out property <BakingTime> baking_time: {
        hours: 0,
        minutes: 0,
        seconds: 0,
    };
    pure callback baking_enabled(bool);

    // Cryocooler
    pure callback cryocooler_set_on(bool);
    in-out property <bool> cryocooler_is_on;

    // Flow meter
    in-out property <bool> water_flow_ok;

    // Light switch
    pure callback light_switch(bool);

    // Program
    pure callback close_program();
    in-out property <bool> admin_mode: false;
    pure callback enter_admin_mode();

    // Pumps
    in-out property <bool> ion_pump_is_on;
    pure callback ion_pump_set_on(bool);
    in-out property <bool> pump_stand_is_on;
    pure callback pump_stand_set_on(bool);

    // Samples
    pure callback edit_sample_name(string, string);
    in-out property <[{pos: string, name: string}]> sample_model: [
        { pos: "A1", name: "" },
        { pos: "A2", name: "" },
        { pos: "B1", name: "" },
        { pos: "B2", name: "" },
        { pos: "C1", name: "" },
        { pos: "C2", name: "" },
        { pos: "D1", name: "" },
        { pos: "D2", name: "" },
    ];

    out property <length> total_height: 400px;
    out property <length> total_width: Const.useable_width - 2 * Const.border_spacing;
    out property <color> border_color: Palette.overlay2;
    out property <length> border_width: 2px;

    // Temperature: Note: A temperature of 0 represents an ERROR state
    in-out property <int> sample_temp; // K
    in-out property <int> bridge_temp; // K
    in-out property <int> cooler_temp; // K
    in property <image> temp_plot;
    in property <int> target_temp; // K
    in property <int> current_power; // W
    pure callback set_setpoint_temp();

    // Vacuum
    in-out property <string> chamber_pressure: "3.20e-10 mbar";
    in-out property <string> transfer_pressure: "1.30e-7 mbar";
    in property <image> vacuum_plot;

    // Valves: callbacks and button settings indicators
    pure callback transfer_valve_set_open(bool);
    in-out property <bool> transfer_valve_is_open;
    pure callback pump_valve_set_open(bool);
    in-out property <bool> pump_valve_is_open;
    pure callback vent_valve_set_open(bool);
    in-out property <bool> vent_valve_is_open;

    // Valve and pump states: for status indicator
    in-out property <ValveOrPumpState> transfer_valve_state: ValveOrPumpState.UndefinedOrError;
    in-out property <ValveOrPumpState> pump_valve_state: ValveOrPumpState.UndefinedOrError;
    in-out property <ValveOrPumpState> pump_stand_state: ValveOrPumpState.UndefinedOrError;
    in-out property <ValveOrPumpState> vent_valve_state: ValveOrPumpState.UndefinedOrError;
    in-out property <ValveOrPumpState> ion_pump_state: ValveOrPumpState.UndefinedOrError;

    // Logging
    in-out property <[string]> log_messages: [];

    // TODO: remove the following debug
    pure callback test_button_pressed();
    in-out property <string> test_button_text: "";
    in-out property <bool> test_button_state: false;
}
