import { Const, TabButton } from "elements.slint";
import { Palette } from "palette.slint";

import { HomeScreen } from "screen_home.slint";
import { CryoScreen } from "screen_cryo.slint";
import { VacuumScreen } from "screen_vacuum.slint";
import { SettingsScreen } from "screen_settings.slint";

import { SampleEditDialog } from "samples.slint";
import { Logic } from "logic.slint";

export { SampleEditDialog, Logic } 

export component AppWindow inherits Window {
    in-out property <int> current_index: 3;
    callback current_index_changed(int);

    current_index_changed(new_index) => {
        root.current_index = new_index;
    }


    x: 0px;
    y: 0px;
    width: Const.screen_width;
    height: Const.screen_height;
    background: Palette.bg;

    TabButton {
        index: 0;
        current_index: root.current_index;
        icon: @image-url("imgs/house.svg");

        TouchArea {
            clicked => {
                root.current_index_changed(0);
            }
        }
    }

    TabButton {
        index: 1;
        current_index: root.current_index;
        icon: @image-url("imgs/snowflake.svg");

        TouchArea {
            clicked => {
                root.current_index_changed(1);
            }
        }
    }

    TabButton {
        index: 2;
        current_index: root.current_index;
        icon: @image-url("imgs/gauge.svg");

        TouchArea {
            clicked => {
                root.current_index_changed(2);
            }
        }
    }

    TabButton {
        index: 3;
        current_index: root.current_index;
        icon: @image-url("imgs/gear.svg");

        TouchArea {
            clicked => {
                root.current_index_changed(3);
            }
        }
    }

    HomeScreen {
        current_index: root.current_index;
    }

    CryoScreen {
        current_index: root.current_index;
    }

    VacuumScreen {
        current_index: root.current_index;
    }

    SettingsScreen {
        current_index: root.current_index;
    }
}
