import { MyWindow } from "elements.slint";

import { Const } from "consts.slint";
import {
    NormalText,
    BigSwitch,
    SmallSwitch,
    InfoArea,
    LongButton,
    PictogramButton,
    InfoAreaSmall,
    StatusOkErr,
    MyHorizontalLayout,
    MyVerticalLayout,
    H3Text,
    H2Text,
    RegularButton,
    NormalText,
} from "elements.slint";
import { Palette } from "palette.slint";

import { TimePickerPopup, TextEdit, ListView } from "std-widgets.slint";
import { Logic } from "logic.slint";

component Baking inherits Rectangle {
    width: Const.screen_width / 2 - Const.border_spacing * 1.5;
    height: 380px;

    background: Palette.bg_area;
    border_radius: Const.border_radius_large;

    MyVerticalLayout {
        alignment: space-between;

        H2Text {
            text: "Baking";
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            Rectangle {
                border_radius: Const.border_radius_small;
                border-width: 2px;
                border-color: Palette.overlay2;
                width: tm_text.width + Const.border_spacing * 8;
                height: tm_text.height + Const.border_spacing * 2;
                background: Logic.baking_is_enabled ? Palette.red : Palette.blue;

                tm_text := H2Text {
                    text: ((Logic.baking_time.hours < 10) ? "0" : "") + Logic.baking_time.hours + ((Logic.baking_time.minutes < 10) ? ":0" : ":") + Logic.baking_time.minutes + ((Logic.baking_time.seconds < 10) ? ":0" : ":") + Logic.baking_time.seconds;
                    color: Palette.crust;
                }
            }
        }

        HorizontalLayout {
            spacing: 5px;
            alignment: center;
            property <length> button_width: 85px;

            RegularButton {
                enabled: !Logic.baking_is_enabled;
                width: button_width;
                text: "- h";
                clicked => {
                    if (Logic.baking_time.hours > 0) {
                        Logic.baking_time.hours -= 1;
                    }
                }
            }

            RegularButton {
                enabled: !Logic.baking_is_enabled;
                width: button_width;
                text: "+ h";
                clicked => {
                    Logic.baking_time.hours += 1;
                }
            }

            Rectangle {
                width: 20px;
            }

            RegularButton {
                enabled: !Logic.baking_is_enabled;
                width: button_width;
                text: "-10 min";
                clicked => {
                    if (Logic.baking_time.minutes >= 10) {
                        Logic.baking_time.minutes -= 10;
                    } else if (Logic.baking_time.minutes > 0) {
                        Logic.baking_time.minutes = 0;
                    }
                }
            }

            RegularButton {
                enabled: !Logic.baking_is_enabled;
                width: button_width;
                text: "+10 min";
                clicked => {
                    Logic.baking_time.minutes += 10;
                }
            }

            Rectangle {
                width: 20px;
            }

            RegularButton {
                enabled: !Logic.baking_is_enabled;
                width: button_width;
                text: "Clear";
                clicked => {
                    Logic.baking_time = { hours: 0, minutes: 0, seconds: 0 };
                }
            }
        }

        HorizontalLayout {
            padding: Const.border_spacing;
            spacing: Const.border_spacing;
            alignment: end;
            RegularButton {
                enabled: Logic.admin_mode && Logic.baking_is_enabled;
                text: "Stop";
                clicked => {
                    Logic.baking_enabled(false);
                    Logic.baking_is_enabled = false;
                }
            }

            RegularButton {
                enabled: Logic.admin_mode && !Logic.baking_is_enabled;
                text: "Start";
                clicked => {
                    Logic.baking_enabled(true);
                    Logic.baking_is_enabled = true;
                }
            }
        }
    }
}

export component SettingsScreen inherits MyWindow {
    index: 3;

    MyVerticalLayout {
        spacing: Const.border_spacing;
        MyHorizontalLayout {
            MyVerticalLayout {

                LongButton {
                    text: "Admin mode";
                    enabled: true;
                    background: Logic.admin_mode ? Palette.button_on : Palette.button_off;
                    clicked => {
                        Logic.enter_admin_mode();
                    }
                }

                LongButton {
                    text: "Exit program";
                    enabled: true;
                    clicked => {
                        Logic.close_program();
                    }
                }

                // FIXME: Test button to be removed
                LongButton {
                    text: Logic.test_button_text;
                    clicked => {
                        Logic.test_button_pressed();
                    }
                }
            }

            // FIXME: Remove the following examples: commented out components as demos
            // StatusOkErr {
            //     title: "StatusOkErr: Err";
            //     ok: false;
            // }
            //
            // StatusOkErr {
            //     title: "StatusOkErr: Ok"; }
            //
            // BigSwitch { }
            //
            // SmallSwitch { }
            //
            // InfoArea {
            //     title: "Cold temperature";
            //     text_color: Palette.blue;
            // }

            MyVerticalLayout {

                Baking { }

                // HorizontalLayout {
                //     alignment: end;
                //     PictogramButton {
                //         enabled: true;
                //         clicked => {
                //             Logic.close_program();
                //         }
                //     }
                // }
            }
        }

        H3Text {
            x: Const.border_spacing;
            text: "Log messages:";
            horizontal-alignment: left;
        }

        Rectangle {
            x: Const.border_spacing;
            width: Const.useable_width - 2 * Const.border_spacing;
            height: 250px;

            ListView {

                property <int> cnt: 0;

                for data[idx] in Logic.log_messages: Rectangle {
                    height: 25px;
                    background: mod(idx, 2) == 0 ? Palette.mantle : Palette.crust;

                    Text {
                        x: 0;
                        font-size: 12pt;
                        color: Palette.text;
                        text: data;
                        horizontal-alignment: left;
                    }
                }
            }
        }
    }
}
