import { MyWindow } from "elements.slint";

import { Const } from "consts.slint";
import {
    BigButton,
    BigSwitch,
    NormalText,
    LongButton,
    LightSwitch,
    SmallSwitch,
    InfoArea,
    PictogramButton,
    StatusOkErr,
    InfoAreaSmall,
    MyVerticalLayout,
    MyHorizontalLayout,
} from "elements.slint";
import { Palette } from "palette.slint";
import { Samples } from "samples.slint";
import { Logic } from "logic.slint";

export component HomeScreen inherits MyWindow {
    index: 0;

    MyVerticalLayout {

        MyHorizontalLayout {

            InfoArea{
                title: "Sample temperature";
                title_color: Palette.rosewater;
                text_color: (Logic.sample_temp > 0 && Logic.sample_temp < 120) ? Palette.blue : Palette.red;
                text: (Logic.sample_temp == 0) ? "Error" : Logic.sample_temp + " K";
            }

            InfoAreaSmall {
                title: "Chamber";
                title_color: Palette.sky;
                text: Logic.chamber_pressure;
            }

            InfoAreaSmall {
                title: "Transfer";
                title_color: Palette.yellow;
                text: Logic.transfer_pressure;
            }
        }

        MyHorizontalLayout {

            MyHorizontalLayout {
                alignment: start;
                padding-left: 0px;
                padding-right: 0px;

                BigButton{
                    enabled: true;  // no need for admin mode
                    text: "Start Sample Transfer";
                    clicked() => {
                        Logic.initiate_sample_transfer();
                        debug("Initiate sample transfer");
                    }
                }

                BigSwitch {
                    enabled: true;  // no need for admin mode
                    title: "Vacuum Chamber";
                    right_side: Logic.chamber_is_pumped;
                    left_text: "Vent";
                    right_text: "Pump";
                    switched(set_pumped) => {
                        Logic.set_chamber_is_pumed(set_pumped);  // bool
                        debug("Vacuum set pumped: ",  set_pumped);
                    }
                }
            }

            LightSwitch {
                activated: Logic.light_is_on;
                clicked(val) => {
                    Logic.light_switch(val);
                }
            }
        }

        Samples { }
    }
}
