import { MyWindow } from "elements.slint";

import { NormalText, MyHorizontalLayout, MyVerticalLayout, SmallSwitch, VacuumStateCircle } from "elements.slint";
import { Const } from "consts.slint";

import { Palette } from "palette.slint";
import { Logic, ValveOrPumpState } from "logic.slint";

export component VacuumScreen inherits MyWindow {
    index: 2;

    // Vacuum system image
    vi := Image {
        x: Const.border_spacing;
        y: Const.border_spacing;
        source: @image-url("imgs/vacuum_system.svg");
    }

    VacuumStateCircle {
        state: Logic.ion_pump_state;
        x: vi.x + 53px;
        y: vi.y + 76px;
    }

    VacuumStateCircle {
        state: Logic.pump_stand_state;
        x: vi.x + 689.798px; // turbo
        y: vi.y + 76px; // turbo
    }

    VacuumStateCircle {
        state: Logic.pump_valve_state;
        x: vi.x + 484px; // pump valve
        y: vi.y + 76px; // pump valve
    }

    VacuumStateCircle {
        state: Logic.transfer_valve_state;
        x: vi.x + 269px; // transfer valve
        y: vi.y + 201px; // transfer valve
    }

    VacuumStateCircle {
        state: Logic.vent_valve_state;
        x: vi.x + 689.798px; // vent valve
        y: vi.y + 136.587px; // vent valve
    }

    NormalText {
        x: vi.x + 140px;  // position of chamber in inkscape
        y: vi.y + 12px;

        width: 278px;  // size of chamber in inkscape
        height: 148px;

        horizontal-alignment: center;
        vertical-alignment: center;

        color: Palette.sky;
        text: "Chamber\n" + Logic.chamber_pressure;
    }

    NormalText {
        x: vi.x + 279.039px - self.width;  // position of pipe between valve and dock in inkscape
        y: vi.y + 272.102px - self.height / 2;

        width: 160px;  // empirical...
        height: 80px;  // empirical...

        horizontal-alignment: center;
        vertical-alignment: center;

        color: Palette.yellow;
        text: "Transfer\n" + Logic.transfer_pressure;
    }

    // Legend
    Rectangle {
        property<length> spacing: Const.border_spacing / 3 * 2;
        property<length> text_x_gap: 40px;
        property<length> text_y_gap: -5px;

        width: longest_text.x + longest_text.width + spacing;
        height: 5 * Const.border_spacing / 3 * 2 +  4 * on_circ.height;

        border-radius: Const.border_radius_small;

        // calculated from image
        x: Const.border_spacing + 737.912px - self.width; 
        y: Const.border_spacing + 336.113px - self.height;

        background: Palette.button_off;

        on_circ := VacuumStateCircle {
            state: ValveOrPumpState.OpenOrOn;
            x: spacing;
            y: spacing;
        }


        NormalText {
            x: on_circ.x + text_x_gap;
            y: on_circ.y + text_y_gap;
            text: "Open/On";
        }

        off_circ := VacuumStateCircle {
            state: ValveOrPumpState.ClosedOrOff;
            x: spacing;
            y: 2 * spacing + self.height;
        }

        NormalText {
            x: off_circ.x + text_x_gap;
            y: off_circ.y + text_y_gap;
            text: "Closed/Off";
        }

        diff_circ := VacuumStateCircle {
            state: ValveOrPumpState.SetDifferentFromCalled;
            x: Const.border_spacing / 3 * 2;
            y: 3 * spacing +  2 * self.height;
        }

        NormalText {
            x: diff_circ.x + text_x_gap;
            y: diff_circ.y + text_y_gap;
            text: "Set ≠ Actual";
        }

        err_circ := VacuumStateCircle {
            state: ValveOrPumpState.UndefinedOrError;
            x: Const.border_spacing / 3 * 2;
            y: 4 * spacing +  3 * self.height;
        }

        longest_text := NormalText {
            x: err_circ.x + text_x_gap;
            y: err_circ.y + text_y_gap;
            text: "Undefined/Error";
        }
    }

    MyHorizontalLayout {

        Image {
            source: Logic.vacuum_plot;
            y: Const.screen_height / 4 - 12.5px; // empirical...
        }

        MyVerticalLayout {
            SmallSwitch {
                title: "Pump stand";
                right_side: Logic.pump_stand_is_on;
                left_text: "Off";
                right_text: "On";
                switched(set_on) => {
                    Logic.pump_stand_set_on(set_on);  // bool
                }
            }

            SmallSwitch {
                title: "Ion pump";
                right_side: Logic.ion_pump_is_on;
                left_text: "Off";
                right_text: "On";
                switched(set_on) => {
                    Logic.ion_pump_set_on(set_on);  // bool
                }
            }

            SmallSwitch {
                title: "Gauge chamber";
                left_text: "Off";
                right_text: "On";
            }

            SmallSwitch {
                title: "Gauge transfer";
                left_text: "Off";
                right_text: "On";
            }

            SmallSwitch {
                title: "Valve transfer";
                right_side: Logic.transfer_valve_is_open;
                left_text: "Close";
                right_text: "Open";
                switched(set_open) => {
                    Logic.transfer_valve_set_open(set_open);  // bool
                }
            }

            SmallSwitch {
                title: "Valve pump";
                right_side: Logic.pump_valve_is_open;
                left_text: "Close";
                right_text: "Open";
                switched(set_open) => {
                    Logic.pump_valve_set_open(set_open);  // bool
                }
            }

            SmallSwitch {
                title: "Valve vent";
                right_side: Logic.vent_valve_is_open;
                left_text: "Close";
                right_text: "Open";
                switched(set_open) => {
                    Logic.vent_valve_set_open(set_open);  // bool
                }
            }
        }
    }
}
