import { MyWindow } from "elements.slint";

import { BigSwitch, Const, NormalText, LongButton, LightSwitch, SmallSwitch, InfoArea, PictogramButton, StatusOkErr, InfoAreaSmall, MyVerticalLayout, MyHorizontalLayout } from "elements.slint";
import { Palette } from "palette.slint";
import { Samples } from "samples.slint";
import { Logic } from "logic.slint";

export component HomeScreen inherits MyWindow {
    index: 0;

    MyVerticalLayout {

        MyHorizontalLayout {

            InfoAreaSmall {
                title: "Sample temperature";
                text_color: (Logic.sample_temp < 120) ? Palette.blue : Palette.red;
                text: Logic.sample_temp + " K";
            }

            InfoAreaSmall {
                title: "Chamber";
                text: Logic.chamber_pressure;
            }

            InfoAreaSmall {
                title: "Transfer";
                text: Logic.transfer_pressure;
            }
        }

        MyHorizontalLayout {

            MyHorizontalLayout {
                alignment: start;
                padding-left: 0px;
                padding-right: 0px;

                BigSwitch {
                    title: "Cryocooler";
                    right_side: Logic.cryocooler_is_on;
                    left_text: "Off";
                    right_text: "On";
                    switched(right_side_active) => {
                        Logic.cryocooler_set_on(right_side_active);  // bool
                }
                }

                BigSwitch {
                    title: "Transfer valve";
                    right_side: Logic.transfer_valve_is_open;
                    left_text: "Closed";
                    right_text: "Open";
                    switched(right_side_active) => {
                        Logic.transfer_valve_set_open(right_side_active);  // bool
                }
                }
            }

            LightSwitch {
                clicked(val) => {
                    Logic.light_switch(val);
                }
            }
        }

        Samples {
        }
    }
}
