import { Const } from "consts.slint";
import {
    MyVerticalLayout,
    NormalText,
    H2Text,
    RegularButton,
    H3Text,
    H1Text,
    MyHorizontalLayout,
} from "elements.slint";
import { Palette } from "palette.slint";
import { KeyboardLogic } from "keyboard.slint";

export global ProgressWindowLogic {
    pure callback cancel_pressed();
    pure callback done_pressed();
    in-out property <string> title: "Title";
    in-out property <string> messages: "This is a very long message. Let us see if this thing wraps at some point and if it does so, where it will wrap. The goal is that it actually will, but who knows what happens. You can also break a line with backslash n\n\nor even two lines like this";
    in-out property <bool> cancel_possible: true;
    in-out property <bool> done_button_visible: false;
}

export component ProgressWindow inherits Window {
    y: 20px;

    // FIXME: Uncomment the following two lines
    height: 760px;
    width: 1170px;

    background: Palette.bg;
    no-frame: true;

    MyVerticalLayout {

        H1Text {
            text: ProgressWindowLogic.title;
            horizontal-alignment: center;
        }

        MyHorizontalLayout {
        H2Text {
            text: ProgressWindowLogic.messages;
            horizontal-alignment: center;
            wrap: word-wrap;
        }}

        MyHorizontalLayout {
            alignment: center;
            padding-bottom: Const.border_spacing;

            RegularButton {
                enabled: ProgressWindowLogic.cancel_possible;
                text: "Cancel";
                clicked => {
                    ProgressWindowLogic.cancel_pressed();
                }
            }

            RegularButton {
                enabled: ProgressWindowLogic.done_button_visible;
                text: "Done";
                clicked => {
                    ProgressWindowLogic.done_pressed();
                }
            }
        }
    }
}
