M48
; DRILL file {KiCad 9.0.4} date 2025-09-12T15:10:17+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-12T15:10:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X6.1392Y-2.1299
X6.3301Y-2.1299
T2
X6.1274Y-2.0106
X6.3419Y-2.0106
M30
