name: Build and release book
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jontze/action-mdbook@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          mdbook-version: "~0.5.2" # Use a semver compatible string
          use-mermaid: true
          mermaid-version: "~0.17.0"
      - name: Show mdbook version
        run: mdbook --version
      - name: Show mermaid version
        run: mdbook-mermaid --version
      - name: Build book
        working-directory: docs
        run: mdbook build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: docs/book/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
